; PlatformIO — CrowPanel ESP32-S3 5.79" E-Paper (792x272)
; Réglages alignés sur la doc Elecrow (Huge APP, OPI PSRAM)

[env:crowpanel_579]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Liaison série / upload ---
upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
upload_speed = 460800
monitor_speed = 115200

; --- Mémoire (équivalent des réglages Arduino IDE Elecrow) ---
board_build.flash_size = 8MB
board_build.partitions = huge_app.csv   ; "Huge APP (3MB No OTA/1MB SPIFFS)"
board_build.arduino.memory_type = qio_opi ; active la PSRAM OPI

build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=0   ; on programme via la puce UART (usbserial), pas l'USB natif

lib_deps =
    bblanchon/ArduinoJson@^7.2.0
